### PR TITLE
fix(recipes): new step structure and ignoring blank lines

### LINKED ISSUE #226: bug(recipe-contribute): detect and delete a blank newline in ingredients and directions (SMALL)

### LINKED ISSUE #242: fix(recipes): update recipe contribute and details pages to work with new step structure (SMALL)
The database now holds recipe step data in a list format rather than a long string. Both the recipe contribute and details pages need to be updated to work with this new format.

Todo:
- [ ] Update recipe details
- [ ] Update recipe contribute

### PR DESCRIPTION
**Pull request by edbertdai**
`recipe/steps` in the database is now an array instead of a string similar to how `ingredients` is now.
The `recipe-details` and `recipe-contribute` pages are updated to support this change.
This can be tested by creating a new recipe and seeing the results in the database and the corresponding details page.

`recipe-contribute` now ignores blank lines that the user enters in the ingredients and direction text boxes when submitting.

Closes #226 
Closes #242

### CODE REVIEW

File: source/components/recipe-details/recipe-details.js [hunk 1]
```diff
@@ -192,7 +192,14 @@ class RecipeDetails extends YummyRecipesComponent {
       "<ul>" + ingredients + "</ul>";
 
     // Direction box
-    this.shadowRoot.querySelector(".direction-list").innerHTML = recipe.steps;
+    let directions = "";
+
+    for (let i = 0; i < recipe.steps.length; i++) {
+      directions = directions + "<li>" + recipe.steps[i] + "</li>";
```
Comment (jbutera94) [inline source/components/recipe-details/recipe-details.js:198]: You can use `+=`. See below:
```suggestion
      directions += "<li>" + recipe.steps[i] + "</li>";
```

**Review by jbutera94 — APPROVED** [review]
Looks good, left one tiny suggestion.

File: source/components/recipe-details/recipe-details.js (hunk 1 above)
Comment (edbertdai) [reply source/components/recipe-details/recipe-details.js]: Fixed

**Review by jbutera94 — APPROVED** [review]
